sonar.organization=damouu
sonar.projectKey=library-app-comments

sonar.sources=src/application,src/domain,src/infrastructure,src/presentation,src/app.ts,src/bootstrap.ts,src/index.ts
sonar.tests=src/tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8