FROM node:lts-alpine

RUN apk add --no-cache g++ make python3

WORKDIR /app

COPY --chown=node:node package.json package-lock.json ./

USER node

RUN npm ci --ignore-scripts

COPY --chown=node:node src/ ./src

EXPOSE 3000
EXPOSE 9229

CMD ["npm", "run", "dev"]