FROM node:lts-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --ignore-scripts

COPY tsconfig.json ./
COPY src/ ./src

RUN npm run build


FROM node:lts-alpine AS production

ENV NODE_ENV=production

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --omit=dev --ignore-scripts

COPY --from=builder /app/dist ./dist

RUN addgroup -S nodeapp \
    && adduser -S nodeapp -G nodeapp

USER nodeapp

EXPOSE 3000

CMD ["node", "dist/index.js"]