FROM node:lts-alpine AS builder

WORKDIR /app
  
COPY package*.json ./

RUN npm install
  
COPY . .


FROM node:lts-alpine AS runner

ENV NODE_ENV=production

WORKDIR /app
  
COPY package*.json ./
  
RUN npm ci --only=production

COPY --from=builder /app/src ./src

RUN addgroup -S nodeapp && adduser -S nodeapp -G nodeapp
USER nodeapp

EXPOSE 3000

CMD ["node", "src/index.js"]