FROM node:lts-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --ignore-scripts

COPY src/ ./src

EXPOSE 3000
EXPOSE 9229

CMD ["npm", "run", "dev"]