name: YouTrack-Staging

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: github.event.label.name == 'Staging'
    runs-on: ubuntu-latest
    steps:
      - uses: bloobirds-it/action-youtrack-move@2d323980954263fb5ee24772d66207387a21ae12
        with:
          github-token: ${{ secrets.MYWORKFLOW }}
          yt-url: ${{ secrets.YOUTRACK_URL }}
          yt-token: ${{ secrets.YOUTRACK_TOKEN }}
          yt-project-id: "LAC"
          yt-column-triggers: "Test"
          yt-column-target: "Staging"

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf
        with:
          github_token: ${{ secrets.MYWORKFLOW  }}
          labels: automerge
